spring:
  jpa:
     database: POSTGRESQL
     show-sql: true
     hibernate:
        ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/farmaco
    username: postgres
    password: bitzua
server:
   port: 8080 
   
eureka:
  client:
    service-url:
      defaultZone: https://eureka-evaluacion.herokuapp.com/eureka/ #http://localhost:8761/eureka/
      
#para seguridad      
security:
   oauth2:
    resource:
      userInfoUri: https://auth-mito-micro.herokuapp.com/user #http://localhost:9999/user