server:
   port: 8099

eureka:
   client:
      #register-with-eureka: false 
      serviceUrl:
         defaultZone: https://eureka-evaluacion.herokuapp.com/eureka/#http://localhost:8761/eureka/
         
zuul:
   host:
       connect-timeout-millis: 100000 #para seguridad
       socket-timeout-millis: 100000 #para seguridad
   routes:
      uaa:
         path: /uaa/**
         sensitiveHeaders: #para seguridad
         url: https://auth-mito-micro.herokuapp.com #AUTH-SERVER nombre del proveedor autentificacion y autorizacion
      forma1:
         path: /farmacia-micro/**
         sensitiveHeaders:
         url: https://evaluacion-medical.herokuapp.com #http://localhost:8080
      forma2:
         path: /farmacia-api/**
         sensitiveHeaders:
         url: farmacia-micro
#       otro:
#          path: /ejemplo/**
#          sensitiveHeaders:
#          url: http://localhost:3000/
         
         